### ISSUE TITLE
Error message with provenance file

### ISSUE THREAD

**Issue by wongwill86** [seung-lab/cloud-volume#139]
```
  File "/usr/local/lib/python3.6/site-packages/cloudvolume/cloudvolume.py", line 148, in __init__
    self.cache.check_provenance_validity()
  File "/usr/local/lib/python3.6/site-packages/cloudvolume/cacheservice.py", line 236, in check_provenance_validity
    cached_prov = self.get_json('provenance')
  File "/usr/local/lib/python3.6/site-packages/cloudvolume/cacheservice.py", line 252, in get_json
    return storage.get_json(filename)
  File "/usr/local/lib/python3.6/site-packages/cloudvolume/storage.py", line 148, in get_json
    return json.loads(content.decode('utf8'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Not sure if this is intentional or not but the message is not very informative. I've seen something where a 403 forbidden might cause an error in decoding an empty message. Not sure if this is the case right now but it's very hard to figure out what's going on here.

**Comment by william-silversmith** [comment]
Able to recreate the error as follows, but still need to check what network errors cause this to create a more informative message.

```>>> json.loads('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/people/ws9/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/people/ws9/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/people/ws9/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
