### ISSUE TITLE
Can't access single pixels of a volume without specifying a range

### ISSUE THREAD

**Issue by amwilson149** [seung-lab/cloud-volume#149]
Given a volume "vol", I'd like to access a single voxel with a command like the following:

root_id_curr = vol[x_curr, y_curr, z_curr].flatten()

Instead, I have to specify a one-pixel-wide range, as follows, or else I get an error:

root_id_curr = vol[x_curr:x_curr+1, y_curr:y_curr+1, z_curr:z_curr+1].flatten()

**Comment by william-silversmith** [comment]
Is this still an issue? I tried to reproduce it but was unable.

**Comment by william-silversmith** [comment]
Alyssa was able to index individual pixels.

**Comment by william-silversmith** [comment]
This happens when the inputs are cast to numpy integer types e.g. `x = np.uint(12412)`.

```Traceback (most recent call last):
 File "181218_p100_inspect_orph_dend_sa_v_and_l.py", line 55, in <module>
   seg_curr    = vol[x,y,z]
 File "/usr/people/amw7/pinky100_VENV_python3p6/VENV_1/lib/python3.6/site-packages/cloudvolume/cloudvolume.py", line 930, in __getitem__
   (requested_bbox, steps, channel_slice) = self.__interpret_slices(slices)
 File "/usr/people/amw7/pinky100_VENV_python3p6/VENV_1/lib/python3.6/site-packages/cloudvolume/cloudvolume.py", line 775, in __interpret_slices
   slices = generate_slices(slices, minsize, maxsize, bounded=self.bounded)
 File "/usr/people/amw7/pinky100_VENV_python3p6/VENV_1/lib/python3.6/site-packages/cloudvolume/lib.py", line 651, in generate_slices
   start = minsize[index] if slc.start is None else slc.start
AttributeError: 'numpy.uint64' object has no attribute 'start'
```
