### ISSUE TITLE
Parallel doesn't work with AWS s3

### ISSUE THREAD

**Issue by jabae** [seung-lab/cloud-volume#155]
Traceback (most recent call last):
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 83, in __del__
    closefn(conn)
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 99, in <lambda>
    return lambda conn: conn.close()
    self.reset_pool()
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 74, in reset_pool
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/botocore/client.py", line 555, in __getattr__
    self.reset_pool()
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 74, in reset_pool
    closefn(conn)
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 99, in <lambda>
    self.reset_pool()
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 74, in reset_pool
    closefn(conn)
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 99, in <lambda>
    return lambda conn: conn.close()
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/botocore/client.py", line 555, in __getattr__
    closefn(conn)
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/cloudvolume/connectionpools.py", line 99, in <lambda>
    return lambda conn: conn.close()
  File "/usr/people/jabae/.virtualenvs/cloudvolume/lib/python3.5/site-packages/botocore/client.py", line 555, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'close'
    return lambda conn: conn.close()

**Comment by william-silversmith** [comment]
Added https://github.com/seung-lab/cloud-volume/commit/8e16e720793b6f3188e63e7f77bb44efd30cc4d9 to tests.

**Comment by william-silversmith** [comment]
Upgrading cloud-volume fixed the problem.
