### ISSUE TITLE
error from using new kempression

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#201]
I have installed the latest fpzip, but still have an error:
```
Traceback (most recent call last):                                                      
  File "/root/chunkflow/scripts/consume_tasks.py", line 3, in <module>                  
    from cloudvolume import CloudVolume, Bbox                                           
  File "/root/cloud-volume/cloudvolume/__init__.py", line 2, in <module>                
    from .cloudvolume import CloudVolume                                                
  File "/root/cloud-volume/cloudvolume/cloudvolume.py", line 33, in <module>            
    from .skeletonservice import PrecomputedSkeletonService                             
  File "/root/cloud-volume/cloudvolume/skeletonservice.py", line 21, in <module>        
    from .txrx import cdn_cache_control                                                 
  File "/root/cloud-volume/cloudvolume/txrx.py", line 12, in <module>                   
    from . import lib, chunks                                                           
  File "/root/cloud-volume/cloudvolume/chunks.py", line 31, in <module>                 
    import fpzip                                                                        
  File "__init__.pxd", line 918, in init fpzip                                          
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 
om C header, got 192 from PyObject                                                      

```
any idea of the problem?
looks like your pypi build is not usable in my docker image. Is that an AVX2 or other compiler feature problem?

**Comment by jingpengw** [comment]
```
```

**Comment by jingpengw** [comment]
```
this is often an issue with incompatible numpy versions. numpy 1.16 broke several things, i think this might be one of them?
can you make sure you're using the latest version?
in the worst case, you can do `pip install fpzip --no-binary :all:`
this will install fpzip from source
which python version are you using?
```
@william-silversmith I am using latest version fpzip.
should I use numpy<=1.15 or latest numpy?
I am using python 3.6

**Comment by william-silversmith** [comment]
I compiled against 1.16.

**Comment by jingpengw** [comment]
I just tried numpy 1.15.4, still have same error. 
will try your new build and also the `no-binary` trick.

**Comment by jingpengw** [comment]
the `no-binary` trick works!
