### ISSUE TITLE
Python3 info decode error

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#24]
```
>>> img=cloudvolume.CloudVolume('gs://neuroglancer/piriform_v0/image/7_7_40/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chrisj/dev/test-cloudvolume/cloudvolume/lib/python3.5/site-packages/cloudvolume/cloudvolume.py", line 94, in __init__
    self.refresh_info()
  File "/home/chrisj/dev/test-cloudvolume/cloudvolume/lib/python3.5/site-packages/cloudvolume/cloudvolume.py", line 154, in refresh_info
    self.info = json.loads(infojson)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by william-silversmith** [comment]
Resolved in #25
