### ISSUE TITLE
setup.py install is not working

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#241]
in travis build
```
Reading https://pypi.org/simple/cloud-volume/
Downloading https://files.pythonhosted.org/packages/98/7f/8791a1e11390ae6c4b40331b0eb09bedfc99d6d91bbf0abd84a60403d060/cloud-volume-0.53.5.tar.gz#sha256=3e55518b5e8fddb39765442528384faacb5df0efcf0d03d28d709732b3b256a3
Best match: cloud-volume 0.53.5
Processing cloud-volume-0.53.5.tar.gz
Writing /tmp/easy_install-9mx845qa/cloud-volume-0.53.5/setup.cfg
Running cloud-volume-0.53.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9mx845qa/cloud-volume-0.53.5/egg-dist-tmp-6yb8ckiv
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-9mx845qa/cloud-volume-0.53.5/setup.py", line 65, in <module>
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.6.7/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.6.7/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.6.7/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
```

**Comment by fcollman** [comment]
``` 
 File "/Users/forrestc/anaconda3/envs/celltypes/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
```
(adding the last line.. i can confirm similar issues with 0.53.0 and 0.53.5

**Comment by william-silversmith** [comment]
Can you point me to a repo with the travis error? Unable to reproduce locally (I'm not using conda though).

**Comment by jingpengw** [comment]
@william-silversmith 
actually I was using setup.py rather than pip
https://travis-ci.org/seung-lab/chunkflow/jobs/559753777

**Comment by william-silversmith** [comment]
Okay, I can reproduce this locally.

**Comment by william-silversmith** [comment]
I was able to fix it locally using this: https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data

I ended up deleting my local build directory. However, it then died trying to build DracoPy without scikit-build.

**Comment by william-silversmith** [comment]
https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install

**Comment by william-silversmith** [comment]
Is there a reason you have to use setup.py install versus pip?

**Comment by jingpengw** [comment]
not really, just want to delete the `requirements.txt` and integrate everything together.

**Comment by william-silversmith** [comment]
I don't think I'm going to officially support this use case.
