### ISSUE TITLE
graphene cutout service bug

### ISSUE THREAD

**Issue by fcollman** [seung-lab/cloud-volume#251]
```Python
File "/Users/forrestc/ConnectomeStack/EM_mesh_analysis/em_mesh_analysis/Fix_mesh.py", line 133, in get_fixed_seg_mask
    id_list]
  File "/Users/forrestc/anaconda3/envs/celltypes/lib/python3.7/site-packages/cloud_volume-0.56.1-py3.7.egg/cloudvolume/frontends/graphene.py", line 96, in __getitem__
    root_ids = list(slices.pop())
AttributeError: 'tuple' object has no attribute 'pop'
```

Not sure if i'm just using it wrong, but putting the 4th dimension as a set of IDs to lookup appears to break the cloud-volume graphene cutout front end. 

Here is the code that was calling it 

```Python
        id_list = [nuc_seg_id]
        if cell_seg_id is not None:
            id_list.append(cell_seg_id)
        seg_cutout = seg_vol[mins[0]:maxs[0],
                             mins[1]:maxs[1],
                             mins[2]:maxs[2],
                             id_list]
```

**Comment by fcollman** [comment]
I think there is something further wrong with this code... on the graphene_test branch #254 I discovered this odd difference

```Python
In [19]: cv.download(bbox, mask_base=True, root_ids=[648518346349523869])                                                                  
Downloading:   0%|                                                                                                   | 0/1 [00:00<?, ?it/s]
Out[19]: 
array([[[[648518346349523869]],

        [[648518346349523869]],

        [[648518346349523869]]],


       [[[648518346349523869]],

        [[648518346349523869]],

        [[648518346349523869]]],


       [[[648518346349523869]],

        [[648518346349523869]],

        [[648518346349523869]]],


       [[[648518346349523869]],

        [[648518346349523869]],

        [[648518346349523869]]]], dtype=uint64)

In [20]: bbox                                                                                                                              
Out[20]: Bbox([54314, 22606, 1136],[54318, 22609, 1137], dtype=int32)

In [21]: cv[54314, 22606, 1136,[648518346349523869]]                                                                                       
Downloading:   0%|                                                                                                   | 0/1 [00:00<?, ?it/s]
Out[21]: array([[[0]]], dtype=uint64)
```

**Comment by fcollman** [comment]
removing some try/excepts i found this 

```Python 
Traceback (most recent call last):
  File "test_slices.py", line 18, in <module>
    print(cv[54314, 22606, 1136,[648518346349523869]])
  File "/Users/forrestc/anaconda3/envs/celltypes/lib/python3.7/site-packages/cloudvolume/frontends/graphene.py", line 100, in __getitem__
    parallel=self.parallel, root_ids=root_ids
  File "/Users/forrestc/anaconda3/envs/celltypes/lib/python3.7/site-packages/cloudvolume/frontends/graphene.py", line 81, in download
    img = fastremap.mask_except(img, root_ids, in_place=True)
  File "fastremap.pyx", line 265, in fastremap.mask_except
TypeError: Argument 'labels' has incorrect type (expected list, got list_iterator)
```

**Comment by william-silversmith** [comment]
Resolved with both implementation and design changes in #254
