### ISSUE TITLE
(minor) 0 byte .gz file throws non-informative exception

### ISSUE THREAD

**Issue by shangmu** [seung-lab/cloud-volume#315]
Somehow a few 0 byte .gz files was created due to exhaustion of disk space while creating/writing to a volume. Upon accessing (including writing to) such locations non-informative exception is thrown:

Partial stack trace:
```
Traceback (most recent call last):
  File "./XXX.py", line 114, in YYY
    test = cv_out[bounds]
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/frontends/precomputed.py", line 528, in __getitem__
    img = self.download(requested_bbox, self.mip)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/frontends/precomputed.py", line 564, in download
    img = self.image.download(bbox, mip, parallel=parallel)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/__init__.py", line 138, in download
    green=self.config.green,
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 139, in download
    green=green 
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 291, in download_chunks_threaded
    green=green,
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/scheduler.py", line 72, in schedule_jobs
    return schedule_threaded_jobs(fns, concurrency, progress, total)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/scheduler.py", line 19, in schedule_threaded_jobs
    tq.put(wrap(fn))
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/threaded_queue.py", line 257, in __exit__
    self.wait(progress=self.with_progress)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/threaded_queue.py", line 227, in wait
    self._check_errors()
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/threaded_queue.py", line 191, in _check_errors
    raise err
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/threaded_queue.py", line 153, in _consume_queue
    self._consume_queue_execution(fn)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/threaded_queue.py", line 180, in _consume_queue_execution
    fn()
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/scheduler.py", line 14, in wrapped
    return fn()
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 273, in process
    enable_cache, compress_cache
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py", line 246, in download_chunk
    content = stor.get_file(filename)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/storage/storage.py", line 164, in get_file
    content = compression.decompress(content, encoding, filename=file_path)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/compression.py", line 33, in decompress
    return gunzip(content)
  File "/opt/conda/lib/python3.7/site-packages/cloudvolume/compression.py", line 93, in gunzip
    hex(first_two_bytes[0]), hex(first_two_bytes[1])), hex(gzip_magic_numbers[0]), hex(gzip_magic_numbers[1]))
IndexError: list index out of range
```

**Comment by shangmu** [comment]
Wow that was fast. Kudos
