### ISSUE TITLE
Precomputed files not generated

### ISSUE THREAD

**Issue by manoaman** [seung-lab/cloud-volume#319]
Hi, I'm trying to convert tiff stacks to a precomputed chunk volumes.  However, I'm experiencing errors when 3d chunk size is set to chunk_size=[64,64,64].  Files don't seem to get generated. chunk_size=[512, 512, 1] did work.   Is tiff stack supported for data conversion?

Thanks,
m

```
  Non-Aligned writes are disabled by default. There are several good reasons 
  not to use them. 

  1) Memory and Network Inefficiency
    Producing non-aligned writes requires downloading the chunks that overlap
    with the write area but are not wholly contained. They are then painted
    in the overlap region and added to the upload queue. This requires
    the outer shell of the aligned image to be downloaded painted, and uploaded. 
  2) Race Conditions
    If you are using multiple instances of CloudVolume, the partially overlapped 
    chunks will be downloaded, partially painted, and uploaded. If this procedure
    occurs close in time between two processes, the final chunk may be partially
    painted. If you are sure only one CloudVolume instance will be accessing an
    area at any one time, this is not a problem.

  If after reading this you are still sure you want non-aligned writes, you can
  set non_aligned_writes=True.

  Alignment Check: 
    Mip:             0
    Chunk Size:      [64 64 64]
    Volume Offset:   [0 0 1]
    Received:        Bbox([0, 0, 6],[4029, 7711, 7], dtype=int32) 
    Nearest Aligned: Bbox([0, 0, 1],[4029, 7711, 65], dtype=int32)

Processing C0_Z009.tif
Could not convert data to an integer.
```

```
info = CloudVolume.create_new_info(  # 'image' or 'segmentation'
                                     # can pick any popular uint
                                     # other options: 'jpeg', 'compressed_segmentation' (req. uint32 or uint64)
                                     # X,Y,Z values in nanometers
                                     # values X,Y,Z values in voxels
                                     # rechunk of image X,Y,Z in voxels
                                     # X,Y,Z size in voxels
    num_channels=1,
    layer_type='image',
    data_type='uint16',
    #data_type='uint64',
    encoding='raw',
    resolution=[6500, 6500, 1],
    voxel_offset=[0, 0, 1],
    chunk_size=[64, 64, 64],
    #volume_size=[8368, 2258, 12208],
    #volume_size=[2015, 3856, 218],
    volume_size=[4029, 7711, 1073],
    )
```

**Comment by william-silversmith** [comment]
Hi manoaman, 

Can you show me the rest of your script? I'll probably be able to identify the issue pretty easily. How big is each TIFF file?

Sorry for the delay in getting back to you!

Will

**Comment by manoaman** [comment]
Hi William,

Thank you for your response!  Yes, I will attach the rest of my script here.  There are 219 image stacks (0~218).  Downsized original files (72MB each) to 3.2MB.  

```
% /usr/local/ImageMagick/bin/identify -format "%w x %h %x x %y" C0_Z000.tif
806 x 1542 49759.2 PixelsPerCentimeter x 49758.1 PixelsPerCentimeter
```

Thank you for your advise.
manoaman

[cloudvolume_script.txt](https://github.com/seung-lab/cloud-volume/files/4396406/cloudvolume_script.txt)

**Comment by william-silversmith** [comment]
Ah I see the problem. Uploading your TIFF stacks in 64<sup>3</sup> chunks is going to be more difficult because you'll need to upload 64 slices at a time to avoid non-aligned writes (alternatively you can turn on non-aligned writes if you use a single process only, multiprocess will corrupt your data with a race condition). 

I would recommend uploading the data as a stack of single slices, then "rechunking" the data using CloudVolume (using either Igneous or the `transfer_to` function). This will abstract away the difficulties of handling these TIFF files.

**Comment by william-silversmith** [comment]
Also, your volume size was set to a single Z slice, which works but doesn't really make sense with 64x64x64 chunking.

**Comment by manoaman** [comment]
hi William, thanks for your feedback.  I didn't quite understand the two steps and "rechunking" so I hope you can clarify me.  I am attaching two scripts for 1. "upload a stack of single slices", and 2. "rechunking" the precomputed data.  It would be great if you can point out in the attached snippet.  Thanks!!

[upload.txt](https://github.com/seung-lab/cloud-volume/files/4405649/upload.txt)
[rechunking.txt](https://github.com/seung-lab/cloud-volume/files/4405652/rechunking.txt)


> I would recommend uploading the data as a stack of single slices, then "rechunking" the data using CloudVolume (using either Igneous or the transfer_to function). This will abstract away the difficulties of handling these TIFF files.

**Comment by manoaman** [comment]
Is this correct for Igneous?  Snippet attached.  (This is I believe running after upload script.)

https://github.com/seung-lab/igneous
[igneous.txt](https://github.com/seung-lab/cloud-volume/files/4405684/igneous.txt)

**Comment by william-silversmith** [comment]
Shoot, I forgot that `transfer_to` doesn't allow for changing the chunk size. My bad. You're correct to use Igneous, which carves the dataset into blocks and then can rechunk. 

The Vec class you're getting an error for is not necessary, you can just pass it a tuple. However, you can alternatively do: `from cloudvolume import Vec`

**Comment by william-silversmith** [comment]
You'll also want to use something more like this in igneous.txt:
```
  tasks = tc.create_transfer_tasks(
    src_layer_path, dest_layer_path, 
    chunk_size=(64,64,64), shape=(1024,1024, 128),
    fill_missing=False, translate=(0,0,0), 
    bounds=None, mip=0, preserve_chunk_size=True,
    encoding=None, skip_downsamples=False,
    delete_black_uploads=False
  )
```

**Comment by william-silversmith** [comment]
Sometimes there's an issue with LocalTaskQueue where it hangs. If you run into this, you can run single-core using MockTaskQueue which is more reliable.

**Comment by manoaman** [comment]
I think I'm getting close to rechunking.  The only problem I'm seeing now is that the last z range (193-220) volume chunks are not generated.  And it is probably related to the errors I'm getting.  How do I circumvent this error to generate these chunks?

```
Generated chunks.
/rechunked/200_200_1000/768-806_0-64_129-193.gz
/rechunked/200_200_1000/768-806_0-64_1-65.gz
/rechunked/200_200_1000/768-806_0-64_65-129.gz

-------
/rechunked/200_200_1000/768-806_0-64_193-220.gz  -----> Not generated chunk which Neuroglancer expects
```

Errors:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "igneous.py", line 33, in <module>
    tq.insert_all(tasks)
  File "/igneous/venv/lib/python3.5/site-packages/taskqueue/taskqueue.py", line 629, in __exit__
    self._process()
  File "/igneous/venv/lib/python3.5/site-packages/taskqueue/taskqueue.py", line 620, in _process
    for _ in executor.imap(_task_execute, self.queue):
  File "/igneous/venv/lib/python3.5/site-packages/multiprocess/pool.py", line 731, in next
    raise value
cloudvolume.exceptions.AlignmentError: 
  Non-Aligned writes are disabled by default. There are several good reasons 
  not to use them. 

  1) Memory and Network Inefficiency
    Producing non-aligned writes requires downloading the chunks that overlap
    with the write area but are not wholly contained. They are then painted
    in the overlap region and added to the upload queue. This requires
    the outer shell of the aligned image to be downloaded painted, and uploaded. 
  2) Race Conditions
    If you are using multiple instances of CloudVolume, the partially overlapped 
    chunks will be downloaded, partially painted, and uploaded. If this procedure
    occurs close in time between two processes, the final chunk may be partially
    painted. If you are sure only one CloudVolume instance will be accessing an
    area at any one time, this is not a problem.

  If after reading this you are still sure you want non-aligned writes, you can
  set non_aligned_writes=True.

  Alignment Check: 
    Mip:             0
    Chunk Size:      [1024 1024    1]
    Volume Offset:   [0 0 1]
    Received:        Bbox([0, 0, 1],[64, 64, 65], dtype=int32) 
    Nearest Aligned: Bbox([0, 0, 1],[806, 1024, 65], dtype=int32)
```

**Comment by manoaman** [comment]
LocalTaskQueue and MockTaskQueue both seemed to hang on me.  Although `from cloudvolume import Vec` did work!

> Sometimes there's an issue with LocalTaskQueue where it hangs. If you run into this, you can run single-core using MockTaskQueue which is more reliable.

**Comment by william-silversmith** [comment]
If the last chunk was not generated, it probably means your volume size or offset is not set right. The Precomputed standard allows for the last chunk to be truncated to the edge of the bounding box, but no other chunks may be truncated.  

Glancing at your output above, it looks like the info file in the destination does not have the right chunking parameter. Try deleting the existing destination and running it again. 

Let me know how it goes!

**Comment by manoaman** [comment]
So I tried run again, and also attempted to change `info` chunk size and here is what I am still getting.  Exception is attached.  Any idea what might be missing here?

[exception.txt](https://github.com/seung-lab/cloud-volume/files/4416717/exception.txt)


`{
  "data_type": "uint16",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          64,
          64,
          64 
        ]
      ],
      "encoding": "raw",
      "key": "200_200_1000",
      "resolution": [
        200,
        200,
        1000
      ],
      "size": [
        806,
        1542,
        219
      ],
      "voxel_offset": [
        0,
        0,
        1 
      ]
    }
  ],
  "type": "image"
}`

----

**Comment by william-silversmith** [comment]
Are you able to visualize the source volume using either the microviewer or neuroglancer?

**Comment by william-silversmith** [comment]
https://github.com/seung-lab/cloud-volume/wiki/%CE%BCViewer

**Comment by manoaman** [comment]
Original source, and rechunked volumes both did show up on Neuroglancer yesterday.  I did modify for the target's `info` with 64 chunksize manually after running a script.  And then  I realized on the Neuroglancer where rechunked source were giving 404 for those missing .gz files (truncated?).  Is this suppose to happen?  I also not familiar how chunk volume in cube will show up in the Neuroglancer.  Is it suppose to look clearer on y-z, x-z planes? 

`source`
```
{
  "data_type": "uint16",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          1024,
          1024,
          1
        ]
      ],
      "encoding": "raw",
      "key": "200_200_1000",
      "resolution": [
        200,
        200,
        1000
      ],
      "size": [
        806,
        1542,
        219
      ],
      "voxel_offset": [
        0,
        0,
        1
      ]
    }
  ],
  "type": "image"
}
```

`dist`
```
{
  "data_type": "uint16",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          64,
          64,
          64
        ]
      ],
      "encoding": "raw",
      "key": "200_200_1000",
      "resolution": [
        200,
        200,
        1000
      ],
      "size": [
        806,
        1542,
        219
      ],
      "voxel_offset": [
        0,
        0,
        1
      ]
    }
  ],
  "type": "image"
}
```

**Comment by william-silversmith** [comment]
Oh once you generate the volume, you can't change the info file so easily. Neuroglancer and CloudVolume uses the values in it to look for certain file names. If you change it after, it will look for the wrong filenames. Otherwise, your info files look good.

If the image looks clearer on an off-axis plane, then somehow the image was originally uploaded transposed. You can try reuploading the image in different orientations to see what works best.

**Comment by manoaman** [comment]
Hmm... I'm a bet confused.  In the previous post, I manually changed `chunk_sizes` in the `info` file to 64,64,64 because it is generating 1024,1024,1.

When rechunking the volumes, shouldn't my igneous script generate a `info` file with chunk_sizes set to 64,64,64 ?  Following script is generating the exact same `info` file in the `dest_layer_path` when I compared to that in `src_layer_path`. 

```
from taskqueue import LocalTaskQueue
import igneous.task_creation as tc

# Mesh on 8 cores, use True to use all cores
src_layer_path = 'precomputed://file://output'
dest_layer_path = 'file://output2'
with LocalTaskQueue(parallel=8) as tq:

  tasks = tc.create_transfer_tasks(
    src_layer_path, dest_layer_path, 
    chunk_size=None, shape=Vec(64, 64, 64),
    fill_missing=False, translate=(0,0,0), 
    bounds=None, mip=0, preserve_chunk_size=True,
    encoding=None, skip_downsamples=False,
    delete_black_uploads=False
  )
  tq.insert_all(tasks)

print("Done!")
```

**Comment by william-silversmith** [comment]
The `chunk_size` parameter determines the file chunk size during the transfer. The `shape` parameter determines how large a cutout is acquired before rechunking and uploading. For example, use `chunk_size=(64,64,64)` and `shape=(512,512,512)` You need to carefully shape the tasks so that the shape is a multiple of the chunk_size. You don't need to worry about the chunk size of the source because CloudVolume will read a consistent cutout from any chunk size.

**Comment by manoaman** [comment]
That did do the trick.  And I have two questions.  1. Resolution seems rough for the rechunked data.  How do I preserve the same resolution?  2. Original tiffs were downsized to 20%. (72MB to 3.2MB) Should I be using original tiff size since there seems to be `preserve_chunk_size` and `skip_downsamples` which handles the downsampling?

![Screen Shot 2020-04-02 at 4 02 19 PM](https://user-images.githubusercontent.com/47464840/78307725-6b0f4e80-74fb-11ea-9cb8-f25e003ddd50.png)

![Screen Shot 2020-04-02 at 4 02 28 PM](https://user-images.githubusercontent.com/47464840/78307724-69de2180-74fb-11ea-8b16-e843cfeb29d4.png)

**Comment by william-silversmith** [comment]
The chunk_size is the underlying storage unit and is unrelated to the resolution of the image. If you didn't upload the original sized TIFFs, the resolution will be reduced in CloudVolume/Neuroglancer. Once the originals are uploaded, you can run downsampling to generate an image pyramid which could be more convenient for viewing.

**Comment by manoaman** [comment]
What is `shape` and how big the size should be?  It seems that if I have this value not big enough, the entire image will not show up.

**Comment by william-silversmith** [comment]
Igneous works by dividing the image into a grid of tasks. The shape is the size of the task. If the shape is not a multiple of the chunk size, the transfer will not work correctly. If the shape is not a multiple of two of the chunk size, then the downsamples will not work either.

**Comment by manoaman** [comment]
I tried with `shape=Vec(3200, 3200, 3200)`.  And I'm only seeing 200_200_1000, 400_400_1000 chunks are generated.  Should 800_800_1000, 1600_1600_1000, 3200_3200_1000, 6400_6400_1000 chunks folders generated as well?  I'm getting AlignmentError exception and I have doubts if I set the `shape` properly.  Is 3200 multiple of chunk size?  

[exception.txt](https://github.com/seung-lab/cloud-volume/files/4432952/exception.txt)

[info.txt](https://github.com/seung-lab/cloud-volume/files/4432949/info.txt)

**Comment by william-silversmith** [comment]
Try using `shape=(512,512,512)`, the shape you are using would on its own have created a 32 GiB array. A 512^3 array is only 128 MB. 512 is also 8 x 64, which means you can generate 3 levels of downsampling from it.

**Comment by manoaman** [comment]
I tried with `shape=(512,512,512)` and I do see 200_200_1000, 400_400_1000, 800_800_1000, 1600_1600_1000 downsampled levels are generated.  Info file is attached.  In Neuroglancer, do I need to manually choose which downsample level to use?  It seems 1600-1600-1000 is always called for the chunk data.  Also for this specific downsampled level, I'm seeing the latter part of x-axis is not filled with chunks.  Seems like getting 404 errors for missing chunks.  I'm also attaching igneous script.  Any insights where I could fix?  Thanks!

[igeous.txt](https://github.com/seung-lab/cloud-volume/files/4441952/igeous.txt)

![Screen Shot 2020-04-06 at 8 28 05 PM](https://user-images.githubusercontent.com/47464840/78628117-26135100-7848-11ea-81d6-1e9cd0c74e22.png)

![Screen Shot 2020-04-06 at 8 36 53 PM](https://user-images.githubusercontent.com/47464840/78628314-a639b680-7848-11ea-8802-fe08b7a37dd0.png)

[info.txt](https://github.com/seung-lab/cloud-volume/files/4441933/info.txt)

**Comment by manoaman** [comment]
There seems to be 11 failed chunks for 1600_1600_1000 level.  One thing I noticed when running Igneous, I saw "No factors generated" error in my console.  Do you know why this error happens?

`Tasks:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 109/128 [3:11:13<30:41, 96.90s/it]No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([0, 7680, 0],[512, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([512, 7680, 0],[1024, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([1024, 7680, 0],[1536, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([1536, 7680, 0],[2048, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([2048, 7680, 0],[2560, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([2560, 7680, 0],[3072, 7711, 219], dtype=int32)
No factors generated. Image Shape: (512, 31, 219, 1), Downsample Shape: [512  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([3072, 7680, 0],[3584, 7711, 219], dtype=int32)
No factors generated. Image Shape: (445, 31, 219, 1), Downsample Shape: [445  31 219], Volume Shape: [4029 7711  219], Bounds: Bbox([3584, 7680, 0],[4029, 7711, 219], dtype=int32)`

![Screen Shot 2020-04-07 at 11 56 27 AM](https://user-images.githubusercontent.com/47464840/78708676-5d751280-78c7-11ea-9319-0303404080dd.png)

**Comment by manoaman** [comment]
How do I offset z-stack index when I run `create_transfer_task`? z-stack images are 219 in size but they are index with (0-218) and not (1-219).  I have a feeling my script may be pointing to (1~219).  Could that be an issue with getting `No factors generated` error?

```
  tasks = tc.create_transfer_tasks(
    src_layer_path, dest_layer_path, 
    chunk_size=(64,64,64), shape=Vec(512,512,512),
    fill_missing=False, translate=(0,0,0), 
    bounds=None, mip=0, preserve_chunk_size=True,
    encoding=None, skip_downsamples=False,
    delete_black_uploads=False
  )
```

**Comment by william-silversmith** [comment]
Hi again, I've been a bit busy but I'll get back to your questions in the next day or two. In the meantime, Igneous based its operations off the info file, so if the source info file says it starts at `voxel_offset=(0,0,1)` and so does the destination info file, then there shouldn't be a problem.

The no factors generated error usually happens because the task shape (truncated to the bounding box of the dataset) is not able to generate even a single 2x downsample given the chunk size.

**Comment by manoaman** [comment]
Thanks for responding.  As you mentioned, offset didn't seem to be a problem.  What I see is same no factors generated error usually happening at whenever the task is 85% complete.

Is there a verbose option to print out more detailed logs with `create_transfer_tasks `?

**Comment by william-silversmith** [comment]
Usually, I just go into create_transfer_tasks in task_creation.py or tasks.py and add print statements for these cases.

**Comment by manoaman** [comment]
Hi again,  if I want to create 3d isotropic chunks, where do I specify to get 100 x 100 x 20 voxels size?  My voxel size is 200nm x 200nm x 1000nm, and I want to get 20um x 20um x 20um chunks.  Could this be `translate=(100,100,20)` or `translate=(20,20,20)` ?  Or is this something I need to set in shape cutout?

**Comment by william-silversmith** [comment]
You would specify the chunk size at the `create_transfer_tasks` function. However, unless you are doing something special, it's not necessary as you can extract arbitrary cutouts from a Precomputed volume. If you're interested in downsampling to achieve isotropic voxels, that would be a different question.

**Comment by manoaman** [comment]
I don't know if I understand.  Would you be able to give me an example to understand when you mean by "downsampling to achieve"?  Thanks!

> If you're interested in downsampling to achieve isotropic voxels, that would be a different question.

**Comment by william-silversmith** [comment]
Say you start with 4x4x40 nm voxels. If you downsample it serially by
factors of 2x2x1, you can get to a near isotropic resolution such as
32x32x40.

**Comment by manoaman** [comment]
I see. So in my case, I started with 200_200_1000 nm voxels.  And downsampled to 400_400_1000 nm, 800_800_1000 nm, 1600_1600_1000 by factors of 2x2x1.  And the nearest would be 800_800_1000.

How do I accomplish getting 1000_1000_1000 nm voxels from downsampling in `create_transfer_tasks`?

**Comment by william-silversmith** [comment]
That is a more complicated operation and we do not currently support it
unfortunately...

You can see how we do this using https://github.com/seung-lab/tinybrain/

**Comment by william-silversmith** [comment]
Closing due to inactivity. If you still have questions, please let me know and feel free to reopen!
