### ISSUE TITLE
connecting to a SWIFT s3 storage from local openstack cluster

### ISSUE THREAD

**Issue by ededits** [seung-lab/cloud-volume#582]
Hi everyone!

I am not a cloud-volume user, but setting it up for researchers at my org. We want to utilize a local openstack cluster for a project and I can't figure out how to do it. 

Everything works just fine, when I use local filesystem for processing
```python3
vol = CloudVolume('file://bucket/dataset/layer', info=info)
```

I can interface with my SWIFT storage using REST, s3cmd, or using openstack CLI utilities. So it works and I have connectivity to it. I can also work with it using boto3 library: 

``` python3
import boto3
…
session = boto3.session.Session()
s3 = session.client(
        's3',
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        endpoint_url=endpoint_url,
        config=boto3.session.Config(signature_version='s3v4')
    )
s3.list_buckets()
```
This works and lists my buckets. I can't understand how to properly point at this storage in the CloudVolume call
``` python3
vol = CloudVolume(cloud_path, info=info)
```

What's the correct `cloud_path` for using my own s3? Can I somehow use boto3 session handler? Any help would be much appreciated!

**Comment by william-silversmith** [comment]
Hi ededits!

You can connect to a custom s3 endpoint using this construction: `s3://https://...` where the appropriate URL follows. There is also a facility in CloudFiles for creating an alias for s3 endpoints, however it must be configured on each individual machine.

https://github.com/seung-lab/cloud-files#alias-for-alternative-s3-endpoints

Let me know if this helps!

**Comment by ededits** [comment]
Hi William, thanks for reply! 

This is what I see with `vol = CloudVolume('s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)`:

```python3
----> 1 vol = CloudVolume('s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)
...
...
UnsupportedProtocolError:
Cloud Path must conform to FORMAT://PROTOCOL://BUCKET/PATH
Examples:
  precomputed://gs://test_bucket/em
  gs://test_bucket/em
  graphene://https://example.com/image/em

Supported Formats: None (precomputed), graphene, precomputed, boss, n5
Supported Protocols: gs, file, s3, http, https, mem, matrix, tigerdata

Cloud Path Recieved: s3://https://myexample.edu:8443/swift/v1/ng-test
```

As far as cloud-files, I don't understand what to do with the alias and how to use this alias to create a CloudVolume object... 

Thank you!

**Comment by fcollman** [comment]
are you connecting to a precomputed volume?
If so I think you you wanted to use precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test

I think he was suggesting that you can simplify this with cloudfiles if you ran..

cloudfiles alias add myexample s3://https://myexample.edu:8443/

then you would be able to access things using

precomputed://myexample://swift/v1/ng-test

But you would have to run that on every machine that installed cloudvolume.

**Comment by ededits** [comment]
> 

Hi fcollman! 

With `vol = CloudVolume('precomputed://s3://https://myexample.edu/swift/v1/ng-test', info=info)` I get exactly the same error 

```
UnsupportedProtocolError:
Cloud Path must conform to FORMAT://PROTOCOL://BUCKET/PATH
```

With cloudfiles I get this: 
```
cloudfiles alias add myexample s3://https://myexample.edu:8443/
Traceback (most recent call last):
...
 File "/software/apps/python/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I've tried adding an alias with `cloudfiles alias add myexample https://myexample.edu:8443/`, and this works. Furthermore , I can create a vol object with `vol = CloudVolume('precomputed://myexample://swift/v1/ng-test', info=info)` -- this does not return any errors. But then I can't write to this volume, because: 
```
File ~/py39/lib/python3.9/site-packages/cloudfiles/interfaces.py:614, in HttpInterface.put_file(self, file_path, content, content_type, compress, cache_control, storage_class)
    612 def put_file(self, file_path, content, content_type,
    613              compress, cache_control=None, storage_class=None):
--> 614   raise NotImplementedError()

NotImplementedError:
```
Obviously this alias is pointing at http interface and `put_file` is not supported (which I see in the documentation as well, so, this was expected). 

Thank you!

**Comment by william-silversmith** [comment]
Hi!

Thanks for experimenting with it!

If you need write access, it sounds to me like your first attempt worked
but there was no info file when it used the s3 interface. Would you mind
sharing the full traceback?

Will

**Comment by ededits** [comment]
Hi Will!


Here is a full trace of the cloudvolume call (I hope this is the call you are asking for):

```python3
vol = CloudVolume('precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)
---------------------------------------------------------------------------
UnsupportedProtocolError                  Traceback (most recent call last)
Cell In[15], line 1
----> 1 vol = CloudVolume('precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)

File ~/py39/lib/python3.9/site-packages/cloudvolume/cloudvolume.py:228, in CloudVolume.__new__(cls, cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, agglomerate, secrets, spatial_index_db, lru_bytes)
    225 kwargs = dict(locals())
    226 del kwargs['cls']
--> 228 path = strict_extract(cloudpath)
    229 if path.format in REGISTERED_PLUGINS:
    230   return REGISTERED_PLUGINS[path.format](**kwargs)

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:109, in strict_extract(cloudpath, windows, disable_toabs)
    101 def strict_extract(cloudpath, windows=None, disable_toabs=False):
    102   """
    103   Same as cloudvolume.paths.extract, but raise an additional
    104   cloudvolume.exceptions.UnsupportedProtocolError
   (...)
    107   Returns: ExtractedPath
    108   """
--> 109   path = extract(cloudpath, windows, disable_toabs)
    111   if path.dataset == '' or path.layer == '':
    112     raise UnsupportedProtocolError(cloudpath_error(cloudpath))

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:151, in extract(cloudpath, windows, disable_toabs)
    148 else:
    149   abspath = toabs
--> 151 fmt, protocol, cloudpath = extract_format_protocol(cloudpath)
    153 split_char = '/'
    154 if protocol == 'file':

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:64, in extract_format_protocol(cloudpath)
     61 (proto, cloudpath) = pop_protocol(cloudpath)
     63 if proto is None:
---> 64   raise error # e.g. ://test_bucket, test_bucket, wow//test_bucket
     66 fmt, protocol = None, None
     68 if proto not in (ALLOWED_PROTOCOLS + ALLOWED_FORMATS):

UnsupportedProtocolError:
Cloud Path must conform to FORMAT://PROTOCOL://BUCKET/PATH
Examples:
  precomputed://gs://test_bucket/em
  gs://test_bucket/em
  graphene://https://example.com/image/em

Supported Formats: None (precomputed), graphene, precomputed, boss, n5
Supported Protocols: gs, file, s3, http, https, mem, matrix, tigerdata, mytest

Cloud Path Recieved: precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test
```

Just in case this is relevant, here is `info` definition
```python3
info = CloudVolume.create_new_info(
        num_channels = 1,
        layer_type = 'image', # 'image' or 'segmentation'
        data_type = 'uint16', # can pick any popular uint
        encoding = 'raw', # see: https://github.com/seung-lab/cloud-volume/wiki/Compression-Choices
        resolution = [ 2, 2, 2 ], # X,Y,Z values in nanometers
        voxel_offset = [ 0, 0, 0 ], # values X,Y,Z values in voxels -- specifies the start of the layer
        chunk_size = [ 1024, 1024, 1 ], # rechunk of image X,Y,Z in voxels
        #volume_size = [ 8368, 2258, 12208 ], # X,Y,Z size in voxels
        volume_size = [ 7306, 9979, 3900 ], # X,Y,Z size in voxels
)
```

**Comment by ededits** [comment]
Hi Will!


Here is a full trace of the cloudvolume call (I hope this is the call you are asking for):

```python3
vol = CloudVolume('precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)
---------------------------------------------------------------------------
UnsupportedProtocolError                  Traceback (most recent call last)
Cell In[15], line 1
----> 1 vol = CloudVolume('precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test', info=info)

File ~/py39/lib/python3.9/site-packages/cloudvolume/cloudvolume.py:228, in CloudVolume.__new__(cls, cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, agglomerate, secrets, spatial_index_db, lru_bytes)
    225 kwargs = dict(locals())
    226 del kwargs['cls']
--> 228 path = strict_extract(cloudpath)
    229 if path.format in REGISTERED_PLUGINS:
    230   return REGISTERED_PLUGINS[path.format](**kwargs)

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:109, in strict_extract(cloudpath, windows, disable_toabs)
    101 def strict_extract(cloudpath, windows=None, disable_toabs=False):
    102   """
    103   Same as cloudvolume.paths.extract, but raise an additional
    104   cloudvolume.exceptions.UnsupportedProtocolError
   (...)
    107   Returns: ExtractedPath
    108   """
--> 109   path = extract(cloudpath, windows, disable_toabs)
    111   if path.dataset == '' or path.layer == '':
    112     raise UnsupportedProtocolError(cloudpath_error(cloudpath))

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:151, in extract(cloudpath, windows, disable_toabs)
    148 else:
    149   abspath = toabs
--> 151 fmt, protocol, cloudpath = extract_format_protocol(cloudpath)
    153 split_char = '/'
    154 if protocol == 'file':

File ~/py39/lib/python3.9/site-packages/cloudvolume/paths.py:64, in extract_format_protocol(cloudpath)
     61 (proto, cloudpath) = pop_protocol(cloudpath)
     63 if proto is None:
---> 64   raise error # e.g. ://test_bucket, test_bucket, wow//test_bucket
     66 fmt, protocol = None, None
     68 if proto not in (ALLOWED_PROTOCOLS + ALLOWED_FORMATS):

UnsupportedProtocolError:
Cloud Path must conform to FORMAT://PROTOCOL://BUCKET/PATH
Examples:
  precomputed://gs://test_bucket/em
  gs://test_bucket/em
  graphene://https://example.com/image/em

Supported Formats: None (precomputed), graphene, precomputed, boss, n5
Supported Protocols: gs, file, s3, http, https, mem, matrix, tigerdata, mytest

Cloud Path Recieved: precomputed://s3://https://myexample.edu:8443/swift/v1/ng-test
```

Just in case this is relevant, here is `info` definition
```python3
info = CloudVolume.create_new_info(
        num_channels = 1,
        layer_type = 'image', # 'image' or 'segmentation'
        data_type = 'uint16', # can pick any popular uint
        encoding = 'raw', # see: https://github.com/seung-lab/cloud-volume/wiki/Compression-Choices
        resolution = [ 2, 2, 2 ], # X,Y,Z values in nanometers
        voxel_offset = [ 0, 0, 0 ], # values X,Y,Z values in voxels -- specifies the start of the layer
        chunk_size = [ 1024, 1024, 1 ], # rechunk of image X,Y,Z in voxels
        #volume_size = [ 8368, 2258, 12208 ], # X,Y,Z size in voxels
        volume_size = [ 7306, 9979, 3900 ], # X,Y,Z size in voxels
)
```

**Comment by william-silversmith** [comment]
Oh sorry, I meant when you set the alias as `s3://https://`.

**Comment by ededits** [comment]
Do you mean this:
```
~> cloudfiles alias add mytest s3://https://myexample.edu:8443/swift/v1/ng-test
Traceback (most recent call last):
  File "/home/eud4002/py39/bin/cloudfiles", line 8, in <module>
    sys.exit(main())
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eud4002/py39/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/eud4002/py39/lib/python3.9/site-packages/cloudfiles_cli/cloudfiles_cli.py", line 803, in alias_add
    aliases = json.loads(f.read())
  File "/software/apps/python/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/software/apps/python/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/software/apps/python/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by william-silversmith** [comment]
Ohh oops that looks like a bug on my end. Try creating a file
~/.cloudfiles/aliases.json with file contents: {}

I'll have to fix that in a bit.

**Comment by william-silversmith** [comment]
Hmm, I tried this on my end with no file present and it worked. Try the following:

1. Delete your existing ~/.cloudfiles/aliases.json file
2. Check the permissions on the directory / file
3. Make sure CloudFiles is up-to-date

Let me know if any of that fixes things for you!

**Comment by ededits** [comment]
Hi Will


I think I am one step closer! 

1. I don't know why it didn't work, but I just tried `cloudfiles` again and the following worked just fine
```
cloudfiles alias add myexample s3://https://myexample.edu:8443
```
It created `aliases.json` and all looks good. 

2. CloudVolume call now fails with another error:
```python3
vol = CloudVolume("precomputed://myexample://swift/v1/ng-test", info=info)
....
File ~/py39/lib/python3.9/site-packages/botocore/auth.py:418, in SigV4Auth.add_auth(self, request)
    416 def add_auth(self, request):
    417     if self.credentials is None:
--> 418         raise NoCredentialsError()
    419     datetime_now = datetime.datetime.utcnow()
    420     request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)

NoCredentialsError: Unable to locate credentials
```
I see this is now coming from the boto3 library, so it's trying to create a connection, meaning (I hope) that CloudVolume() call is properly recognizing the `cloudpath` format, it's all compliant and an attempt to create a connection is now passed to a boto3 library. It however is failing to see the credentials. 

Because we are emulating AWS S3, I thought I'd try two things
-- create a `~/.cloudvolume/secrets/aws-secret.json` with 
```
{
  "AWS_ACCESS_KEY_ID": "XXXXXXXXXXXXXX",
  "AWS_SECRET_ACCESS_KEY": "YYYYYYYYYYYYYYYYYYYYYYYYYYY",
}
```
-- create a `~/.aws/credentials` with 
```
[default]
aws_access_key_id=XXXXXXXXXXXXXX
aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYY
```

Of course, access_key and secret here are the same access_key and secret that work in the following snippet:
```python3
import boto3
…
session = boto3.session.Session()
s3 = session.client(
        's3',
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        endpoint_url=endpoint_url,
        config=boto3.session.Config(signature_version='s3v4')
    )
s3.list_buckets()
```

None of these two ideas worked unfortunately. 

I have a feeling that I am very close, please, bear with me :)


Thanks!

**Comment by william-silversmith** [comment]
Ah! I know what's wrong. You need to make a copy or symbolic link to your aws-secret and call it `myexample-secret.json`.

**Comment by william-silversmith** [comment]
Hi! Can you provide the full stack trace? I'm not certain which part of the code is doing that. CloudVolume tries to fetch info and provenance files. You provided the info file, which avoids that call. The provenance file should return "None" and gracefully add in a default object.

**Comment by ededits** [comment]
Definitely, here it is

```python3
In [17]: vol = CloudVolume('precomputed://myexample://swift/v1/test-eugene', info=info)
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
Cell In[17], line 1
----> 1 vol = CloudVolume('precomputed://myexample://swift/v1/test-eugene', info=info)

File ~/py39/lib/python3.9/site-packages/cloudvolume/cloudvolume.py:230, in CloudVolume.__new__(cls, cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, agglomerate, secrets, spatial_index_db, lru_bytes)
    228 path = strict_extract(cloudpath)
    229 if path.format in REGISTERED_PLUGINS:
--> 230   return REGISTERED_PLUGINS[path.format](**kwargs)
    231 else:
    232   raise UnsupportedFormatError(
    233     "Unknown format {}".format(path.format)
    234   )

File ~/py39/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/__init__.py:53, in create_precomputed(cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, secrets, spatial_index_db, lru_bytes, **kwargs)
     34 config = SharedConfiguration(
     35   cdn_cache=cdn_cache,
     36   compress=compress,
   (...)
     43   spatial_index_db=spatial_index_db,
     44 )
     46 cache_service = CacheService(
     47   cloudpath=get_cache_path(cache, cloudpath),
     48   enabled=bool(cache),
     49   config=config,
     50   compress=compress_cache,
     51 )
---> 53 meta = PrecomputedMetadata(
     54   cloudpath, config=config, cache=cache_service,
     55   info=info, provenance=provenance,
     56   max_redirects=max_redirects,
     57   use_https=use_https # for parsing redirects
     58 )
     60 if mesh_dir:
     61   meta.info['mesh'] = str(mesh_dir)

File ~/py39/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/metadata.py:65, in PrecomputedMetadata.__init__(self, cloudpath, config, cache, info, provenance, max_redirects, use_https)
     63 if provenance is None:
     64   self.provenance = None
---> 65   self.refresh_provenance()
     66   if self.cache.enabled:
     67     self.cache.check_provenance_validity()

File ~/py39/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/metadata.py:336, in PrecomputedMetadata.refresh_provenance(self)
    333     self.provenance = DataLayerProvenance(**prov)
    334     return self.provenance
--> 336 self.provenance = self.fetch_provenance()
    337 if self.cache:
    338   self.cache.maybe_cache_provenance()

File ~/py39/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/metadata.py:368, in PrecomputedMetadata.fetch_provenance(self)
    356 """
    357 Refresh the current provenance file from primary storage (e.g. the cloud)
    358 without reference to cache. The cache will not be updated.
   (...)
    365 Returns: dict
    366 """
    367 cf = CloudFiles(self.cloudpath, secrets=self.config.secrets)
--> 368 provfile = cf.get('provenance')
    369 if provfile:
    370   provfile = provfile.decode('utf-8')

File ~/py39/lib/python3.9/site-packages/cloudfiles/cloudfiles.py:98, in parallelize.<locals>.decor.<locals>.inner_decor(*args, **kwargs)
     95 parallel = nvl(parallel, self.parallel, 1)
     97 if parallel == 1:
---> 98   return fn(*args, **kwargs)
    100 progress = params.get("progress", False)
    101 params["progress"] = False

File ~/py39/lib/python3.9/site-packages/cloudfiles/cloudfiles.py:404, in CloudFiles.get(self, paths, total, raw, progress, parallel, return_dict, raise_errors)
    401 total = totalfn(paths, total)
    403 if total == 1:
--> 404   ret = download(first(paths))
    405   if return_dict:
    406     return { ret["path"]: ret["content"] }

File ~/py39/lib/python3.9/site-packages/cloudfiles/cloudfiles.py:389, in CloudFiles.get.<locals>.download(path)
    386   error = err
    388 if raise_errors and error:
--> 389   raise error
    391 return {
    392   'path': path,
    393   'content': content,
   (...)
    398   'tags': tags,
    399 }

File ~/py39/lib/python3.9/site-packages/cloudfiles/cloudfiles.py:374, in CloudFiles.get.<locals>.download(path)
    372 try:
    373   with self._get_connection() as conn:
--> 374     content, encoding, server_hash, server_hash_type = conn.get_file(path, start=start, end=end)
    376   # md5s don't match for partial reads
    377   if start is None and end is None:

File ~/py39/lib/python3.9/site-packages/tenacity/__init__.py:289, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    287 @functools.wraps(f)
    288 def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289     return self(f, *args, **kw)

File ~/py39/lib/python3.9/site-packages/tenacity/__init__.py:379, in Retrying.__call__(self, fn, *args, **kwargs)
    377 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378 while True:
--> 379     do = self.iter(retry_state=retry_state)
    380     if isinstance(do, DoAttempt):
    381         try:

File ~/py39/lib/python3.9/site-packages/tenacity/__init__.py:325, in BaseRetrying.iter(self, retry_state)
    323     retry_exc = self.retry_error_cls(fut)
    324     if self.reraise:
--> 325         raise retry_exc.reraise()
    326     raise retry_exc from fut.exception()
    328 if self.wait:

File ~/py39/lib/python3.9/site-packages/tenacity/__init__.py:158, in RetryError.reraise(self)
    156 def reraise(self) -> t.NoReturn:
    157     if self.last_attempt.failed:
--> 158         raise self.last_attempt.result()
    159     raise self

File /software/apps/python/3.9/lib/python3.9/concurrent/futures/_base.py:433, in Future.result(self, timeout)
    431     raise CancelledError()
    432 elif self._state == FINISHED:
--> 433     return self.__get_result()
    435 self._condition.wait(timeout)
    437 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /software/apps/python/3.9/lib/python3.9/concurrent/futures/_base.py:389, in Future.__get_result(self)
    387 def __get_result(self):
    388     if self._exception:
--> 389         raise self._exception
    390     else:
    391         return self._result

File ~/py39/lib/python3.9/site-packages/tenacity/__init__.py:382, in Retrying.__call__(self, fn, *args, **kwargs)
    380 if isinstance(do, DoAttempt):
    381     try:
--> 382         result = fn(*args, **kwargs)
    383     except BaseException:  # noqa: B902
    384         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File ~/py39/lib/python3.9/site-packages/cloudfiles/interfaces.py:777, in S3Interface.get_file(self, file_path, start, end)
    774   kwargs['Range'] = "bytes={}-{}".format(start, end)
    776 try:
--> 777   resp = self._conn.get_object(
    778     Bucket=self._path.bucket,
    779     Key=self.get_path_to_file(file_path),
    780     **kwargs
    781   )
    783   encoding = ''
    784   if 'ContentEncoding' in resp:

File ~/py39/lib/python3.9/site-packages/botocore/client.py:530, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    526     raise TypeError(
    527         f"{py_operation_name}() only accepts keyword arguments."
    528     )
    529 # The "self" in this scope is referring to the BaseClient.
--> 530 return self._make_api_call(operation_name, kwargs)

File ~/py39/lib/python3.9/site-packages/botocore/client.py:960, in BaseClient._make_api_call(self, operation_name, api_params)
    958     error_code = parsed_response.get("Error", {}).get("Code")
    959     error_class = self.exceptions.from_code(error_code)
--> 960     raise error_class(parsed_response, operation_name)
    961 else:
    962     return parsed_response

ClientError: An error occurred (404) when calling the GetObject operation: Not Found
```

Thanks!

**Comment by william-silversmith** [comment]
If you have a moment, would you mind installing this CloudFiles branch and see if that fixes things for you? I tried handling "NotFound" the same way as "NoSuchKey".

https://github.com/seung-lab/cloud-files/tree/wms_not_found_s3

**Comment by ededits** [comment]
Hi Will!

I see from CloudVolume() class:
```
  secrets: (dict) provide per-instance authorization tokens. If not provided,
        defaults to looking in .cloudvolume/secrets for necessary tokens.
```
so, based on how my `.cloudvolume/secrets/aws-secret.json` looks, I do the following. Unfortunately, I am still unable to get in:
```python3
access_key = 'XXXXXXXXXX'
secret_key = 'YYYYYYYYYY'
secrets = {
     "AWS_ACCESS_KEY_ID": access_key,
     "AWS_SECRET_ACCESS_KEY": secret_key
 }
# no error here, great!
vol = CloudVolume('precomputed://myexample://swift/v1/ng-test', info=info, provenance={}, secrets=secrets)
# trying to actually store data:
vol.commit_info()
>
> ClientError: An error occurred (401) when calling the PutObject operation: Unauthorized
> 
```
Thanks again!

**Comment by william-silversmith** [comment]
Hmm, one problem could be if your S3 region is not us-east-1. If not set AWS_DEFAULT_REGION as well.

**Comment by ededits** [comment]
TBH I don't understand why setting AWS_DEFAULT_REGION would make any effect, I am not talking to an actual amazon endpoint. But with 
```
secrets = {
     "AWS_ACCESS_KEY_ID": access_key,
     "AWS_SECRET_ACCESS_KEY": secret_key,
     "AWS_DEFAULT_REGION": "us-east-1"
 }
```
I see the same error, `ClientError: An error occurred (401) when calling the PutObject operation: Unauthorized`

**Comment by william-silversmith** [comment]
Ack, you're right. Nevermind. I'll need to think some more about this. It is bizarre. If I was in your position, what I would do is set the number of threads to 0 (main thread execution) by hacking the code in cloud-files and using pdb to check that everything matched your test case with boto above. 

Something would reveal itself I would think.

**Comment by ededits** [comment]
Hi Will


I finally got all this to work, thanks so much for all your help! The problem was that a cloudfiles alias should have been 
```{"myexample": {"host": "s3://https://myexample.edu:8443/swift/v1"}}```
**and not**
```{"myexample": {"host": "s3://https://myexample.edu:8443"}}```
It's kinda obvious -- first endpoint handles authorization, and second would not (everything is obvious when you find a solution :) ).  So with this alias and 
```python3
 vol = CloudVolume('precomputed://myexample://testbucket', info=info, provenance={}, secrets=secrets)
```
everything works.

**Comment by ededits** [comment]
Will, I have to apologize, I rushed to a conclusion and gave you some wrong feedback. The real answer is that my endpoint should be `https://myexample.edu:8443/testbucket` and that's it. The `/swift/v1` is a REST API endpoint, and I didn't need to use it in my setup. I don't think you have any bugs related to this, everything seems to work. Sorry for needless confusion and once again -- thanks much for all your help!

Cheers
-e

**Comment by william-silversmith** [comment]
No worries! Thanks for clearing that up. Good luck with your project!

Will
