### ISSUE TITLE
Converting EM Data from N5 to Precomputed Format

### ISSUE THREAD

**Issue by ZhenbangZhang** [seung-lab/cloud-volume#618]
I have EM data in N5 format. How do I convert it to Precomputed format? I'm new to using CloudVolume and not familiar with the  'info' and 'attribute'. Below is the attribute.json of the N5 data.

```JSON
{
    "scales":[[
        1.0,
        1.0,
        1.0
    ]],
    "blockSize": [
        128,
        128,
        64
    ],
    "compression": {
        "level": -1,
        "type": "gzip",
        "useZlib": false
    },
    "dataType": "uint8",
    "dimensions": [
        1275,
        1185,
        1061
    ],
    "pixelResolution": {
        "dimensions": [
            128.0,
            128.0,
            128.0
        ],
        "unit": "nm"
    },
    "transform": {
        "axes": [
            "z",
            "y",
            "x"
        ],
        "order": "C",
        "scale": [
            128.0,
            128.0,
            128.0
        ],
        "translate": [
            60.0,
            60.0,
            60.0
        ],
        "units": [
            "nm",
            "nm",
            "nm"
        ]
    }
}


```

**Comment by ZhenbangZhang** [comment]
> Hi! CloudVolume can read N5 volumes directly using `n5://` instead of `precomputed://`. If you want to convert to precomputed, I haven't tried it myself, but I don't see a reason you couldn't use https://github.com/seung-lab/igneous to transfer the volume and it should materialize as precomputed.

Hi! Thank you for your response. I have converted my data into the `precomputed` format, but I am experiencing some issues when visualizing with Neuroglancer. It seems like the normalization is not working correctly. Below is the `info.json`. 


```JSON
{
  "data_type": "uint8",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          128,
          128,
          1
        ]
      ],
      "encoding": "raw",
      "key": "128.0_128.0_128.0",
      "resolution": [
        128.0,
        128.0,
        128.0
      ],
      "size": [
        1275,
        1185,
        1000
      ],
      "voxel_offset": [
        60,
        60,
        60
      ]
    }
  ],
  "type": "image"
}
```
![image](https://github.com/seung-lab/cloud-volume/assets/88014545/36fbe009-0077-4a4e-97cb-7e85fc149513)

**Comment by william-silversmith** [comment]
Hmm, that's odd. Since the datatype is uint8, there should be no normalization needed. Can you try pulling a cutout from the n5 data with CloudVolume and type `img.viewer()` on the cutout and see if there is data in there?

**Comment by ZhenbangZhang** [comment]
Here's the visualization result of the N5 data.
![d9a3586a9cefb25aefdf3aeed0b31ef](https://github.com/seung-lab/cloud-volume/assets/88014545/bdf4e13c-ad73-421c-907e-3df518d434a9)
![ce9bcb4e1d8304fc2c3f45e2186e598](https://github.com/seung-lab/cloud-volume/assets/88014545/f28049af-55c2-407f-b20f-5000508ca427)
I converted the N5 data into a series of PNG images, then converted them into the precomputed format. Below is the code:
```python
import os
import numpy as np
from cloudvolume import CloudVolume
from PIL import Image
import cv2

input_folder = 'D:/download/nc_data/jrc_mus-heart-1-s4'
output_path = 'file://D:/download/Neuroglancer/zmesh2/precomputed4-jrc_mus-heart-1-s4'

info = CloudVolume.create_new_info(
    num_channels=1, 
    layer_type='image',
    data_type='uint8', 
    encoding='raw',  
    resolution=[128.0, 128.0, 128.0], 
    voxel_offset=[0, 0, 1], 
    chunk_size=[128, 128, 1], 
    volume_size=[1275, 1185, len(os.listdir(input_folder))],  
)

vol = CloudVolume(output_path, info=info)
vol.commit_info()

for z, filename in enumerate(sorted(os.listdir(input_folder))):
    img = cv2.imread(os.path.join(input_folder, filename),0)
    img_array = np.array(img)
    img_array = img_array[:, :, np.newaxis]  
    vol[:, :, z+1] = img_array
```
I am sure that the series of PNG images is correct, and I suspect that the issue might be with the code.

**Comment by william-silversmith** [comment]
One tip, if you don't need to, don't make your resolution floating point, you trigger floating point logic that can be buggy for some things, though with 0 it's probably not a big deal.

Also, I would recommend making the chunk size bigger (maybe 512x512x1 or 1024x1024x1). Very small chunks slow down image loading and strain the file system.

This is really weird. Are you sure that img_array has non-zero data in it? The code looks ok to me.

**Comment by william-silversmith** [comment]
Another possibility is to do something like this:

```python
from cloudvolume import CloudVolume

n5cv = CloudVolume("n5://...")
n5cv.image.transfer_to("precomputed://...", encoding="png")
```

**Comment by ZhenbangZhang** [comment]
The PNG image data is as follows:
![dd25f29e93e3f00e9e627c25195d472](https://github.com/seung-lab/cloud-volume/assets/88014545/45e5f7ce-d962-465b-9d41-477ddc12680e)

Additionally, I tried changing the resolution to `int` and maked the chunk size bigger, but that didn't seem to help.

I also tried using the following code:

```python
n5cv = CloudVolume('n5://file://D:/download/Neuroglancer/jrc_mus-heart-1/em/fibsem/s4', parallel=True, progress=True,cache_locking=True)
n5cv.image.transfer_to("precomputed://file://D:/download/Neuroglancer/zmesh2/precomputed6-jrc_mus-heart-1-s4", encoding="png")
```

However, I got the following error:

```python
Traceback (most recent call last):
  File "D:\download\Neuroglancer\precomputed.py", line 10, in <module>
    n5cv = CloudVolume('n5://file://D:/download/Neuroglancer/jrc_mus-heart-1/em/fibsem/s4',parallel=True, progress=True) 
  File "C:\Users\dell\.conda\envs\neuro\lib\site-packages\cloudvolume\cloudvolume.py", line 233, in __new__
    return REGISTERED_PLUGINS[path.format](**kwargs)
  File "C:\Users\dell\.conda\envs\neuro\lib\site-packages\cloudvolume\datasource\n5\__init__.py", line 28, in create_n5  
    config = SharedConfiguration(
TypeError: __init__() missing 1 required positional argument: 'cache_locking'
```

**Comment by william-silversmith** [comment]
Sorry about the second suggestion. I realized after I posted it that cross-format transfers aren't supported. I might get something working in Igneous soon. 

I was asking specifically about whether there is anything in image_arr, to make sure the pngs are loading into memory correctly. You can check with `assert np.any(image_arr)` The ones on disk look okay.

**Comment by ZhenbangZhang** [comment]
Thank you for your response. I have added `np.any(image_arr)` to the previous code, but it seems that this is not the issue.
```python
import os
import numpy as np
from cloudvolume import CloudVolume
from PIL import Image
import cv2

input_folder = 'D:/download/nc_data/jrc_mus-heart-1-s4'
output_path = 'file://D:/download/Neuroglancer/zmesh2/precomputed9-jrc_mus-heart-1-s4'

info = CloudVolume.create_new_info(
    num_channels=1, 
    layer_type='image',
    data_type='uint8', 
    encoding='raw',  
    resolution=[128, 128, 128], 
    voxel_offset=[0, 0, 0], 
    chunk_size=[512, 512, 1], 
    volume_size=[1275, 1185, len(os.listdir(input_folder))],  
)

vol = CloudVolume(output_path, info=info)
vol.commit_info()
for z, filename in enumerate(sorted(os.listdir(input_folder))):
    img = cv2.imread(os.path.join(input_folder, filename), 0)
    if np.any(img):
        img = img[:, :, np.newaxis]
        vol[:, :, z] = img
    else:
        print(f"{filename} contains only zero elements.")
        break
    
```

**Comment by william-silversmith** [comment]
Ohh I think I know what the problem is. You're writing to disk, so that means that the way the files are stored is with a compression file extension like `.gz` which is missed by naive static web servers.


Use the following commands:

```
pip install igneous-pipeline
igneous view file://D:/download/Neuroglancer/zmesh2/precomputed9-jrc_mus-heart-1-s4
```

This will launch a more intelligent server that can communicate with Neuroglancer.

**Comment by ZhenbangZhang** [comment]
Thank you very much! I can now see the 3D structure properly. Besides using igneous, are there other methods to handle the `.gz` issue? (since my data is on Windows, but igneous doesn't seem to support Windows 10) Thanks again!

**Comment by william-silversmith** [comment]
Can you show the error you are seeing? I don't have regular access to Windows but I try to support it.

It's been a while since I've dealt with this so apologies for only starting to remember all the tricks. CloudVolume also includes a server, but there's no command line: 

```python
cv = CloudVolume("file://D:/download/Neuroglancer/zmesh2/precomputed9-jrc_mus-heart-1-s4")
cv.viewer()
```

I think some web servers like Apache or Nginx have configurations or extensions that handle this issue too.

**Comment by ZhenbangZhang** [comment]
ok,it's throwing an error
```
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_609-610 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_392-393 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_391-392 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_610-611 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_390-391 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_611-612 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_612-613 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_389-390 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_388-389 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_613-614 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_614-615 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_387-388 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_386-387 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_128_128/0-512_512-1024_615-616 HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2024 15:35:13] code 404, message File not found
127.0.0.1 - - [02/Jul/2024 15:35:13] "GET /precomputed8-jrc_mus-heart-1-s4/128_1
```

**Comment by william-silversmith** [comment]
That's from `cv.viewer()`?

**Comment by ZhenbangZhang** [comment]
Oh, sorry, this is the error obtained using [cors_webserver.py](https://github.com/google/neuroglancer/tree/master). I previously had issues with cross-origin (CORS) requests when using `viewer()`, so I've been using `cors_webserver.py`. However, I found that using `cv.viewer()` now works properly.
![fe8c79b4fded484e8944abb02f1c0ba](https://github.com/seung-lab/cloud-volume/assets/88014545/bcb3be3a-1471-4696-827b-ef571cc894b8)

**Comment by jasper-tms** [comment]
fyi if you don't mind having your data be uncompressed (not gzipped) and therefore take up more disk space, you can specify `compress=False` in your cloudvolume constructor and then they won't be gzipped. Quite the coincidence, I was actually just coming back to this repo to look at my notes from when I asked Will about this on a previous issue (https://github.com/seung-lab/cloud-volume/issues/578#issuecomment-1465302264) and just happened to notice that the most recently opened issue was a user dealing with the same thing.

**Comment by william-silversmith** [comment]
FYI in the release yesterday, `transfer_to` will now work with n5->precomputed (but not precomputed->n5 as I haven't written an n5 writing capability).

**Comment by ZhenbangZhang** [comment]
Hi, I successfully visualized the 3D mesh using igneous, but I encountered an issue. When I first enter the visualization interface, the 3D window does not display the mesh. I need to manually select the label to visualize the mesh. Is there a way to automatically visualize the mesh for all labels?
![image](https://github.com/user-attachments/assets/b82c0051-4b6d-447c-a558-4f71d328a530)

**Comment by william-silversmith** [comment]
Unfortunately, the only way to do this is to manipulate the Neuroglancer url or to hack it in the Javascript console. Neuroglancer doesn't have a way to query all the labels as it only loads partial data.

**Comment by ZhenbangZhang** [comment]
Oh, thanks for your reply. I found a notebook that seems to solve my problem. However, I encountered a new issue. In this notebook, `with viewer.txn() as s` is used to create the visualization window. But when I use `with viewer.txn() as s`, I encounter cross-origin (CORS) request issues. So I usually use `CloudVolume.viewer()` to create the visualization window. Is there a way to solve the cross-origin (CORS) request issue, or can `CloudVolume.viewer()` perform similar functions to those in the notebook?

```python

import neuroglancer
import numpy as np

# %% [markdown]
# #  Start a Neuroglancer session from Python and load in public data 

# %%
# Set which client you want to use 
# The commented out line below uses the BRAINCOGS client to get the latest features.
# neuroglancer.set_static_content_source(url='https://neuroglancer-braincogs.appspot.com')
neuroglancer.set_static_content_source() # default is to use Google Client

# %%
# Make a viewer object that represents your connection to a new Neuroglancer session
viewer = neuroglancer.Viewer()

# %%
# Load in the Allen Mouse Brain Atlas 
# This is hosted publicly in Google Cloud -- hence the "gs://" in the source address below
# wanglab-pma is our public Google Cloud bucket where we host the atlases
 
with viewer.txn() as s:
    s.layers["Allen Mouse Brain Atlas"] = neuroglancer.SegmentationLayer(
        source='precomputed://gs://wanglab-pma/allenatlas_2017',
    )
print(viewer)

# %% [markdown]
# Click the link above and it should bring you to a Neuroglancer session with the Allen Mouse Brain Brain Atlas loaded. That link will be active for as long as this jupyter notebook session is active. 

# %% [markdown]
# # Manipulate the Neuroglancer session from Python
# Pretty much all of the things you can do in the browser with your mouse and keyboard you can also do programmatically from Python. After each code cell look back at your Neuroglancer session to see the changes that were made. I recommend arranging the windows so you can see this jupyter notebook and the Neuroglancer window simultaneously. Here are some examples:

# %%
# Show the entire configuration of the viewer -- these are all things you can change
viewer.state

# %%
# Zoom way out
with viewer.txn() as s:
    s.crossSectionScale = 8

# %%
# Zoom back in
with viewer.txn() as s:
    s.crossSectionScale = 1

# %%
# Change the position you are looking at
with viewer.txn() as s:
    s.position = [135,514,144] # Somewhere in Crus I in the Cerebellum

# %%
# Only look at sagittal planes
with viewer.txn() as s:
    s.layout = 'xy'

# %%
# Rotate brain
with viewer.txn() as s:
    s.cross_section_orientation = [0, 0, -np.cos(45*np.pi/180), np.cos(45*np.pi/180)]

# %%
# Select segments by ID 
with viewer.txn() as s:
    s.layers["Allen Mouse Brain Atlas"].layer.segments = {512, 91, 1025, 1033, 1041, 153, 
                                  1049, 1056, 1064, 936, 944, 951,
                                  957, 1091, 968, 846, 976,
                                  728, 984, 989, 96,
                                  101, 744, 1134, 1007} # only the Cerebellum 

# %%
# Open the right hand control panel and show the selected segments
with viewer.txn() as s:
    s.selectedLayer.layer = "Allen Mouse Brain Atlas"
    s.selectedLayer.visible = True
    s.layers["Allen Mouse Brain Atlas"].tab = "segments"
    s.selectedLayer.size=500 # sets the width of the right hand panel

# %%
# Decrease saturation
with viewer.txn() as s:
    s.layers[0].saturation = 0.5

# %%
# Change color of one of the segments
with viewer.txn() as s:
    s.layers["Allen Mouse Brain Atlas"].segment_colors[1007] = "#a83c32"

# %%
# Merge all of the segments shown so they all have the same color
with viewer.txn() as s:
    s.layers["Allen Mouse Brain Atlas"].equivalences = [(512, 91, 1025, 1033, 1041, 153, 
                                  1049, 1056, 1064, 936, 944, 951,
                                  957, 1091, 968, 846, 976,
                                  728, 984, 989, 96,
                                  101, 744, 1134, 1007)]

# %%
# Undo the merge and reset the segments
with viewer.txn() as s:
    s.layers["Allen Mouse Brain Atlas"].equivalences = []
    s.layers["Allen Mouse Brain Atlas"].layer.segments = {512, 91, 1025, 1033, 1041, 153, 
                                  1049, 1056, 1064, 936, 944, 951,
                                  957, 1091, 968, 846, 976,
                                  728, 984, 989, 96,
                                  101, 744, 1134, 1007}

# %%
# Toggle the yellow bounding box, RGB coordinate axes, scale bar
with viewer.txn() as s:
    s.showDefaultAnnotations = False # turn off yellow bounding box
    s.show_axis_lines=False # turn off axes
    s.show_scale_bar = False

# %%
# Change background color
with viewer.txn() as s:
    s.cross_section_background_color = "#ffffff" # white

# %%
# Bring saturation back up
with viewer.txn() as s:
    s.layers[0].saturation = 1.0

# %%
# Hide the side panel
with viewer.txn() as s:
    s.selectedLayer.visible = False

# %%
# Load in some custom point annotations
counter=0
annotation_layer_name = 'my_annotation_layer'
points = [
    [85,488,144,1056], # x,y,z,segment_id
    [106, 501, 144,1064],
    [137, 516, 144,1025],
    [188,500,144,1033],
    [142,449,144,728],
   
]
with viewer.txn() as s:
    s.layers[annotation_layer_name]=neuroglancer.AnnotationLayer()
    # Link the annotation layer to the atlas layer 
    s.layers[annotation_layer_name].linkedSegmentationLayer['segments'] = "Allen Mouse Brain Atlas"
    annotations=s.layers[annotation_layer_name].annotations
    
    for (x,y,z,segid) in points:
        pt=neuroglancer.PointAnnotation(point=[x, y, z],id=f'point{counter}',segments=[[segid]])
        annotations.append(pt)
        counter+=1

# %%
# Load in a custom line annotation
counter=0
annotation_layer_name = 'my_annotation_layer'
lines = [
    [(62,458,142),(182,490,143)], # (x1,y1,z1),(x2,y2,z2)   
]
with viewer.txn() as s:

    annotations=s.layers[annotation_layer_name].annotations
    print(annotations)
    for (pointA,pointB) in lines:
        pt=neuroglancer.LineAnnotation(pointA=pointA,
                                       pointB=pointB,id=f'line{counter}')
        annotations.append(pt)
        counter+=1

# %%
viewer.state

# %%
# Show brain regions and points in 3D 
# Hide the side panel
with viewer.txn() as s:
    s.layout = "xy-3d"
    s.showSlices=True
    s.projectionOrientation = [-0.2832767367362976, -0.26628902554512024, -0.696902871131897, 0.6026365756988525]
    s.projection_scale = 700
    s.cross_section_scale = 0.5
    s.layers[0].object_alpha=0.2

# %%
# Take a screenshot using the webdriver
from neuroglancer import webdriver as webd

# %%
# Start the webdriver which should open a new window which clones your viewer
webdriver = webd.Webdriver(viewer, headless=False,)

# %% [markdown]
# If you get errors starting the webdriver you may need to do "pip install selenium" into your ng conda environment. You may also need to download the "chromedriver" program if you are using Google Chrome. https://chromedriver.chromium.org/downloads. Put the chromedriver exectuable in your path and then retry running this notebook

# %%
webdriver.driver.set_window_size(1200,800)

# %%
# Hide the top control bar and layer names
with viewer.config_state.txn() as s:
    s.show_ui_controls = False
#     s.show_panel_borders = True
#     s.show_layer_panel = True
#     s.show_help_button= True
#     s.show_location= True

# %%
# Take the screenshot of the webdriver window
screenshot_filename = './test_screenshot.png'
webdriver.driver.save_screenshot(screenshot_filename)

# %%
viewer.state

# %%
# Take a screen "video" (sequence of pngs) of moving through the brain sagittal plane by plane
counter = 0    
for z in range(30,500,10):
    screenshot_filename = './screenshot_{}.png'.format(str(counter).zfill(5))
#     print(screenshot_filename)
    with webdriver.viewer.txn() as s:
        s.position=[113,477,z]
    webdriver.driver.save_screenshot(screenshot_filename)
    counter+=1

# %% [markdown]
# Then make a gif from the sequence of pngs. An easy way to do that with Python is:

# %%
from PIL import Image
import glob, os
 
savename = 'atlasmovie.gif'
# Create the frames
pngs = sorted(glob.glob('./screenshot_00???.png'))
print(pngs)
frames = [Image.open(png) for png in pngs]

# Save into a GIF file that loops forever
frames[0].save(savename, format='GIF', 
               append_images=frames[1:],
               save_all=True,
               duration=200, # milliseconds
               loop=0) 


# %% [markdown]
# That should create the following gif

# %% [markdown]
# <img src="atlasmovie.gif" width=500px/>

# %%
# Create a publicly sharable URL with the current viewer state
# Note that this will only work if the data layers are publicly accessible like in this example
neuroglancer.to_url(viewer.state,prefix="https://neuroglancer-braincogs.appspot.com")

# %% [markdown]
# Copy the above link into a new tab in your browser -- the result should be identical to our first link. Note that this is a static link - if you make more changes to the viewer you will have to regenerate the link.  

# %% [markdown]
# # Load your private light-sheet data into Neuroglancer
# So far we have been using a public dataset (the Allen Mouse Brain Atlas) that is hosted in the cloud. To view private data in Neuroglancer (such as your light-sheet data that lives on bucket), you need to host it yourself (or move it to Google Cloud Storage). Fortunately there is a python package called "cloud-volume" that makes hosting your private data easy. You should have already installed this into your "ng" conda environment as per the instructions at the beginning of the notebook.
# 
# Before your data can be hosted, they need to have been converted to the "precomputed" format. This is part of the light-sheet pipeline that we run for you, so if you have a request at braincogs00.pni.princeton.edu we more than likely have already done this for your data. We store the precomputed data in the "viz/" subfolder for each of your samples on bucket. This path can be found for your request/sample under:
# 
# ```python
# /jukebox/LightSheetData/lightserv/{netid}/{request_name}/{sample_name}/imaging_request_1/viz
# ```
# Replace {netid}, {request_name}, {sample_name} with your information to find your data.
# 
# The precomputed data folder for your raw data are stored in a `raw/` subfolder and a `processing_request_1/` subfolder for the other products, like blended and atlas-registered volumes. For example the precomputed layer for blended channel 488 data the filepath would be:
# 
# ```python
# /jukebox/LightSheetData/lightserv/{netid}/{request_name}/{sample_name}/imaging_request_1/viz/processing_request_1/blended/channel_488/channel488_blended
# ```
#  
# The precomputed data folders have file structures that looks like this:
# ```
# ├── 14400_14400_2000
# ├── 1800_1800_2000
# ├── 28800_28800_2000
# ├── 3600_3600_2000
# ├── 57600_57600_2000
# ├── 7200_7200_2000
# ├── info
# └── provenance
# ```
# The key thing is that there needs to be an `info` file inside the precomputed folder. That is how you know you have found the right folder.
# 
# If you are not sure whether we have created the precomputed layer for you yet, or you cannot find a folder that has contents like what is shown above, please contact lightservhelper@gmail.com or use the #lightsheet-software slack channel for help. Note that if you know how to use braincogs00.pni.princeton.edu to visualize your data (see: https://braincogs00.pni.princeton.edu/FAQ if you don't), when you generate the Neuroglancer link there is a table that shows the filepaths to your precomputed layers once you have filled out the visualization setup form.
# 
# Once you have found the path to your precomputed data, you  need to host it. To do this, open up a Python or iPython session outside of this jupyter notebook and run the following code, but change the `layer_dir` to your light sheet data precomputed layer folder on bucket that you found above.  
# 
# ```python
# from cloudvolume import CloudVolume
# layer_dir = "ENTER THE PATH TO YOUR LAYER HERE"
# vol = CloudVolume(f'file://{layer_dir}')
# vol.viewer(port=1338)
# ```
# 
# **Note:** Make sure to have the ng conda environment activated before running python, otherwise you will get some "module not found" errors. You don't want to run this code in this notebook because it will cause it to hang and you won't be able to run the rest of the cells.

# %% [markdown]
# Once your data are hosted you can make a new Neuroglancer python instance and load them in like this:

# %%
# Makes a new viewer object that is separate from the one we were working with above 
viewer = neuroglancer.Viewer()

# %%
layer_name = "MY CHANNEL NAME" # change this to whatever you want. 
with viewer.txn() as s:
    s.layers[layer_name] = neuroglancer.ImageLayer(
        source='precomputed://http://localhost:1338',
    )
print(viewer)

# %% [markdown]
# Click that link and it will bring you to Neuroglancer with your data loaded in.
# 
# You might notice that the contrast is poor. To change that execute this cell:

# %%
# Change image contrast so the data are more visible
# This inverts the color map (the 1.0- part) and increases the contrast (the factor of 300). 
# Use the d and f keys in the browser to update the contrast to your liking
with viewer.txn() as s:
    imagelayer = s.layers[layer_name]
    imagelayer.shader = """ void main() {emitGrayscale(1.0-toNormalized(getDataValue())*300.0);} """

```

**Comment by william-silversmith** [comment]
Huh that's strange. One thing you can try is cloning the Neuroglancer repo and adding the 'Access-Control-Allow-Origin: *' header, but also that can happen when a URL is unreachable.

If you start the CloudVolume server in another tab, you can maybe direct Neuroglancer to use that URL instead. It will already have that header added.

**Comment by fcollman** [comment]
How are you serving the precomputed data? You have to enable cors on the web server you are using. You can use the neuroglancer local server this should work for debugging, but ultimately you should put it on a web server and that service needs to be configured to enable cors requests… it will vary depending on the server you are using Sent from my mobile device.On Jul 13, 2024, at 1:00 PM, William Silversmith ***@***.***> wrote:﻿
Huh that's strange. One thing you can try is cloning the Neuroglancer repo and adding the 'Access-Control-Allow-Origin: *' header, but also that can happen when a URL is unreachable.
If you start the CloudVolume server in another tab, you can maybe direct Neuroglancer to use that URL instead. It will already have that header added.

**Comment by fcollman** [comment]
This also might be caused by a difference between the server address of the viewer and the source, for example if you are accessing the viewer at 127.0.0.1 and the source is localhost, or perhaps you are using your local IP on your network for the viewer and local host for the source. Sent from my mobile device.On Jul 13, 2024, at 1:00 PM, William Silversmith ***@***.***> wrote:﻿
Huh that's strange. One thing you can try is cloning the Neuroglancer repo and adding the 'Access-Control-Allow-Origin: *' header, but also that can happen when a URL is unreachable.
If you start the CloudVolume server in another tab, you can maybe direct Neuroglancer to use that URL instead. It will already have that header added.
